# Generated by Django 2.1 on 2022-01-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_link', models.CharField(max_length=150)),
                ('blog_image', models.ImageField(upload_to=None)),
                ('blog_content', models.CharField(max_length=2000)),
            ],
        ),
    ]
